name: Publish presentation

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present

    - name: Publish website
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.1.2
      with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: "<your domain name here>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
